# Top-level Makefile

GENERATOR_DIR = generator
GENERATOR_EXECUTABLE = sudoku_generator
ROOT_GEN_EXECUTABLE = $(GENERATOR_EXECUTABLE) # or ./$(GENERATOR_EXECUTABLE) if needed.

SOLVER_DIR = solver
SOLVER_EXECUTABLE = serial_solver
ROOT_SOL_EXECUTABLE = $(SOLVER_EXECUTABLE) # or ./$(SOLVER_EXECUTABLE) if needed.

TARGETS = generate solve

all: ${TARGETS}


generate:
	$(MAKE) -C $(GENERATOR_DIR)
	mv $(GENERATOR_DIR)/$(GENERATOR_EXECUTABLE) $(ROOT_GEN_EXECUTABLE)

solve:
	$(MAKE) -C $(SOLVER_DIR)
	mv $(SOLVER_DIR)/$(SOLVER_EXECUTABLE) $(ROOT_SOL_EXECUTABLE)


clean:
	$(MAKE) -C $(GENERATOR_DIR) clean
	rm -f $(ROOT_GEN_EXECUTABLE)

	$(MAKE) -C $(SOLVER_DIR) clean
	rm -f $(ROOT_SOL_EXECUTABLE)