name: C CI

on:
  push:
    branches: [ "parallel_solver_constraint_pipeline","parallel_solver_constraint" ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: Setup C/C++ Compiler
      id: setup-compiler
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: gcc-latest
    - name: download-openmpi
      shell: bash
      run: wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.9.tar.gz
    - name: extract-openmpi
      shell: bash
      run: tar -xvf ./openmpi-5.0.9.tar.gz
    - name: configure-openmpi
      shell: bash
      run: ./openmpi-5.0.9/configure --prefix="/home/${USER}/.openmpi"
    - name: install-openmpi
      shell: bash
      run: |
        make -j
        sudo make install
    - name: set-openmpi-path
      shell: bash
      run: |
        export PATH=${PATH}:/home/${USER}/.openmpi/bin/
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/${USER}/.openmpi/lib/
        echo ${PATH}
        echo ${LD_LIBRARY_PATH}
    - name: configure
      shell: bash
      run: |
        ls -alp
        pwd
        chmod +x ./setup
        ./setup
        ls -alp
    - name: make
      run: make
    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: built_src_${{matrix.os}}
        path: build/
